# Generated by Django 3.1.3 on 2020-11-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_reservation_time',
            field=models.TimeField(blank=True, help_text='Enter ending parking spot reservation time. Time format: <em>HH:MM</em>', null=True, verbose_name='ending parking spot reservation time'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_reservation_time',
            field=models.TimeField(blank=True, help_text='Enter starting parking spot reservation time. Time format: <em>HH:MM</em>', null=True, verbose_name='starting parking spot reservation time'),
        ),
    ]
